name: Continuous integration

on: push

jobs:
  build:
    name: Build and push configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install envsubst
        run: which envsubst || ( apt-get update -y && apt-get install gettext-base -y )

      - name: Replace variables
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
          SITE_URL: ${{ secrets.SITE_URL }}
          MOODLE_EMAIL: ${{ secrets.MOODLE_EMAIL }}
          MOODLE_SITENAME: ${{ secrets.MOODLE_SITENAME }}
          MOODLE_USERNAME: ${{ secrets.MOODLE_USERNAME }}
          MOODLE_PASSWORD: ${{ secrets.MOODLE_PASSWORD }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MOODLE_MAIL_NOREPLY_ADDRESS: ${{ secrets.MOODLE_MAIL_NOREPLY_ADDRESS }}
          ACME_EMAIL: ${{ secrets.ACME_EMAIL }}
        run: |
             envsubst < docker-compose.yml > docker-compose.yml
             envsubst < traefik.yml > traefik.yml

      - name: Trigger deployment
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
             which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )
             eval $(ssh-agent -s)
             echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
             mkdir -p ~/.ssh
             chmod 700 ~/.ssh
             ssh-keyscan $SITE_URL >> ~/.ssh/known_hosts
             chmod 644 ~/.ssh/known_hosts
             scp -r * deploy@$SITE_URL:/srv/$SITE_URL/
             ssh deploy@$SITE_URL "sudo scripts/update-docker.sh"
